### ISSUE TITLE
Sonoff RF Bridge?

### ISSUE THREAD

**Issue by vk496** [andrew01144/Tasmota-SomfyRTS#4]
Hello,

The Sonoff RF Bridge can be upgraded with Portisch firmware (https://github.com/Portisch/RF-Bridge-EFM8BB1) in order to work with raw frames. Does it mean that it could be a suitable HW for this project?

I didn't found any mention for it, so just opening this issue to ask.

BR,
Valentin

**Comment by andrew01144** [comment]
Hi Valentin,
The Sonoff RF Bridge is not suitable for a few reasons.
- This project uses Berry, which means it needs an ESP32, but the Sonoff uses an ESP8266 (actually, an ESP8285).
- Somfy transmits at 433.42MHz, but the Sonoff transmits at the more standard 433.92MHz.
- The current V2.2 Sonoff RF Bridge cannot be upgraded with Portisch because they use a different MCU. I discovered this when I bought one! [I wish I had seen this first](https://github.com/arendst/Tasmota/discussions/13283).
- I did manage to buy an old V1.0 Sonoff RF Bridge and upgrade it with Portisch, but did not have any success handling protocols with large frames. [This guy found the same limitations](https://github.com/Portisch/RF-Bridge-EFM8BB1/issues/192).

Hope this helps,
Andrew

**Comment by vk496** [comment]
Thank you for the clarification. I have a R2 and I'm able to sniff the codes sent by the remote, so had curiosity about it.

Anyway, thank you for this great project. My antenna will arrive soon and I will be able to use it :)

BR,
Valentín

**Comment by andrew01144** [comment]
> I have a R2 and I'm able to sniff the codes sent by the remote

That's interesting. What firmware and commands did you use?

> My antenna will arrive soon

Let me know how you get on, and if you need any help.

**Comment by vk496** [comment]
Sorry, didn't saw your message.

I did the typical installation of Tasmota and Portisch firmware. My first approach was with yfmos project, but is buggy and unmaintained as I saw
